#================================================== USERS ==================================================
#===========================================================================================================

### REGISTER USERS
POST http://localhost:4000/registerUser
Content-Type: application/json

{
    "email":"helmut.na@gmail.com",
    "password":"contraseña123",
    "name":"Helmut Najarro"
}


### LOGIN
POST  http://localhost:4000/login
Content-Type: application/json

{
    "email":"helmut.na@gmail.com",
    "password":"contraseña123"
}


#================================================== CRYPTO =================================================
#===========================================================================================================

### GET BITCOIN PRICE
GET  http://localhost:4000/bitcoin
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVmcmFhbHZAZ21haWwuY29tIiwibmFtZSI6IkhlbG11dCBOYWphcnJvIiwiaWF0IjoxNjU2NzEyODQ3LCJleHAiOjE2NTY3MTY0NDd9.9-9wTy49CMN8_5X86pxjhsc9VdGdVaqGtUonp_Ahufk


### GET ETHEREUM PRICE
GET  http://localhost:4000/ethereum
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVmcmFhbHZAZ21haWwuY29tIiwibmFtZSI6IkhlbG11dCBOYWphcnJvIiwiaWF0IjoxNjU2NzEyODQ3LCJleHAiOjE2NTY3MTY0NDd9.9-9wTy49CMN8_5X86pxjhsc9VdGdVaqGtUonp_Ahufk